name: Terraform Github Actions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  
#ジョブの権限設定
permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.7.5
  AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
    
 #ワークフロー内のジョブグループ      
jobs:

  #ジョブID
  terraform:

    #ジョブ名
    name: Terraform Setup

    #ジョブ実行するマシンのタイプ
    runs-on: ubuntu-latest
      
    #タスクのグループ  
    steps:

    #GitHubの公式アクション、CI/CDを実行するサーバへチェックアウト
    #https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@master

    #AWS公式のアクション、AWSへの認証
    #https://github.com/aws-actions/configure-aws-credentials
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
 
    #hashicorpの公式のアクション
    #https://github.com/hashicorp/setup-terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~> ${{ env.TF_VERSION }}
 
    - name: Terraform Init
      run: terraform init -upgrade
      working-directory: .terraform
    
    # - name: 'Terraform Init'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: ${{ env.TF_VERSION }}
    #     tf_actions_subcommand: 'init -upgrade'
    #     tf_actions_working_dir: '.'
    #     tf_actions_comment: true
    
    - name: Check validate
      id: validate-check
      run: terraform validate
    
    - name: failure validate
      if: failure() && steps.validate-check.outcome == 'failure'
      run: |
        echo 'terraform syntax check failed'
      
    - name: Terraform Plan
      run: terraform plan
